# Generated by Django 4.1.7 on 2023-03-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.CharField(default='Birthday', max_length=50)),
                ('age', models.IntegerField()),
                ('caketype', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('phone', models.IntegerField()),
                ('orderdate', models.DateField()),
                ('deliverydate', models.DateField()),
            ],
        ),
    ]
